mountaineer/__tests__/dependencies/test_base.py, mountaineer/config.py, mountaineer/database/dependencies.py, mountaineer/dependencies/__init__.py, mountaineer/dependencies/base.py, mountaineer/dependencies/core.py, pyrightconfig.json
Our previous approach to defining core dependencies looked like this:
```python
class CoreDependencies:
@staticmethod
async def dep_1():
pass
@staticmethod
def dep_2(dep_1: int = Depends(dep_1)):
pass
```
The class container was just intended for convenience, so all related dependencies could be located from one place. However, when referencing another dependency in the same file (Depends(dep_1)) we will actually be passing the full staticmethod(func) decorated function, versus the original function itself.
FastAPI's dependency resolution layer recursively resolves dependencies referenced from other dependencies. It supports sync and async dependencies, which it does via `inspect` utilities to figure out what object we're dealing with. Staticmethods break the async inspection since …
=> Fix staticmethods interfering with dep resolution

mountaineer/__tests__/test_watch.py, mountaineer/watch.py
Different package managers have different conventions when it comes to symlinking the current project into the `site-packages` folder. Poetry relies on lowercase `.pth` files, vanilla venvs relies on mirroring the case of the parent project in the dist-info directory, etc.
In this PR we make our watcher a bit more flexible to resolve package names regardless of the case. We also add test coverage for symbolic links and dist links, based on our observation of the local paths installed after we run `create-mountaineer-app` with different configurations.
Addresses: https://github.com/piercefreeman/mountaineer/issues/40
=> Resolve package/filename caps mismatch

mountaineer/__tests__/test_cli.py, mountaineer/cli.py
Our previous dev-server Exception handler would intercept all exceptions encountered during development, including those on the backend that might be validation payloads for the frontend to handle. This broke client side logic that relied on parsing the JSON errors.
This PR relaxes our exception catching logic to only apply to GET requests, which will replace a blank failed page with a more detailed error message.
=> Only show server errors in dev get requests

Makefile, mountaineer/__tests__/client_builder/test_build_schemas.py, mountaineer/client_builder/build_schemas.py, mountaineer/client_builder/builder.py, mountaineer/client_builder/openapi.py
Add support for passing enums from the server to the client views.
When Pydantic models contain enums, they are converted to an OpenAPI property with a list of `enum` values. These values can be a single type or mixed types. When there is a single property type, the property takes on the common type. When mixed type, the enum values are specified without an prevailing type. In this example `MyEnum` is a Python `Enum` and the others inherit from `IntEnum` and `StrEnum` respectively.
```json
{
"$defs": {
"MyEnum": {
"enum": [
"value_1",
5
],
"title": "MyEnum"
},
"MyIntEnum": {
"enum": [
1,
2
],
"title": "MyIntEnum",
"type": "integer"
},
"MyStrEnum": {
"enum": [
"value_1",
"value_2"
],
"title": "MyStrEnum",
"type": "string"
}
},
"properties": {
"a": {
"$ref": "#/$defs/MyStrEnum"
},
"b": { …
```
=> Support enums in client-side useServer

ci_webapp/poetry.lock, mountaineer/__tests__/test_controller.py, mountaineer/controller.py, mountaineer/render.py
Sometimes you need to import 3rd party scripts that are external to your React project (ie. Google Analytics, Stripe, etc). You can inject this in the javascript layer easily enough, but for convenience on page load we add the option of specifying them in the Metadata definition.
```python
Metadata(
scripts=[
ScriptAttribute(src="/script.js")
]
)
```
Following the convention for `<meta>` and <link>` tags, the script tag contains defined attributes for the most common script classes with an additional `optional_attributes` dictionary for the ones that are undefined:
```python
class ScriptAttribute(BaseModel):
src: str
asynchronous: bool = False
defer: bool = False
optional_attributes: dict[str, str] = {}
```
=> Controller-driven def of external scripts

mountaineer/__tests__/test_cli.py, mountaineer/cli.py
Our previous `watch` logic relied on a hard-coded list of packages to support local debugging when working on mountaineer concurrent with a client webapp. We switch this logic to be a bit more general and sniff the local environment for all `mountaineer` and `mountaineer-*` packages.
This watching is still off by default and enabled via `subscribe_to_mountaineer`.
=> Use all mountaineer packages for local reloading

.github/workflows/test_create_mountaineer_app.yml, README.md, ci_webapp/ci_webapp/app.py, ci_webapp/ci_webapp/config.py, ci_webapp/ci_webapp/controllers/complex.py, ci_webapp/ci_webapp/controllers/detail.py, ci_webapp/ci_webapp/controllers/stream.py, ci_webapp/ci_webapp/views/app/complex/page.tsx, ci_webapp/ci_webapp/views/app/detail/page.tsx, ci_webapp/ci_webapp/views/app/home/page.tsx, ci_webapp/ci_webapp/views/app/stream/page.tsx, create_mountaineer_app/create_mountaineer_app/templates/project/[project_name]/app.py, create_mountaineer_app/create_mountaineer_app/templates/project/[project_name]/config.py, create_mountaineer_app/create_mountaineer_app/templates/project/[project_name]/views/__init__.py, docs/metadata.md, docs/postcss.md, mountaineer/__tests__/client_builder/test_builder.py, mountaineer/__tests__/conftest.py, mountaineer/__tests__/test_app.py, mountaineer/__tests__/test_config.py, mountaineer/__tests__/test_paths.py, mountaineer/__tests__/test_watch.py, mountaineer/app.py, mountaineer/client_builder/builder.py, mountaineer/config.py, mountaineer/controller.py, mountaineer/paths.py, mountaineer/watch.py
Our client-code generation pipeline creates a series of typescript files for use in client projects. These are all placed within the `_server` folders embedded within the application views. To access interfaces and helper functions, clients might need to import from multiple of these sub-files.
```tsx
import { useServer } from './_server/useServer';
import { MyModel } from './_server/models';
```
The specific names of these files are an implementation detail. For convenience, this PR adds a `index.ts` file that aggregates and re-exports all of these client objects from the component files. This allows a single import statement to collect all of the objects that the given view will need:
```tsx
import { useServer, MyModel } from './_server';
```
More details: …
=> Add rollup import for _server

ci_webapp/ci_webapp/controllers/home.py, mountaineer/__tests__/actions/test_passthrough.py, mountaineer/__tests__/actions/test_sideeffect.py, mountaineer/__tests__/client_builder/test_build_actions.py, mountaineer/actions/fields.py, mountaineer/actions/passthrough.py, mountaineer/actions/sideeffect.py, mountaineer/app.py, mountaineer/client_builder/build_actions.py, mountaineer/client_builder/openapi.py, mountaineer/static/api.ts, mountaineer/static/ssr_polyfills.js
`@passthrough` functions provide some syntactic sugar over standard POST API endpoints, since most endpoints want to return objects for use on the client side.
Previous PRs added:
- Object streaming support via [async generators](https://github.com/piercefreeman/mountaineer/pull/57)
- Returning [JSONResponse](https://github.com/piercefreeman/mountaineer/commit/803dd21c5b79a7348fac4f91807f45f58598d035), to provide additional headers during passthroughs and sideeffects
This PR adds stronger typehinting to define which endpoints support which kind of return functions, so mypy/pyright should throw an error early if you try to use an incompatible function signature. We also add support for returning arbitrary starlette Response objects in `passthrough` functions:
```python …
```
=> Allow passthroughs to return raw responses

.github/workflows/test.yml, mountaineer/__tests__/client_builder/test_build_schemas.py, mountaineer/__tests__/client_builder/test_builder.py, mountaineer/__tests__/test_cli.py, mountaineer/__tests__/test_watch.py, mountaineer/cache.py, mountaineer/cli.py, mountaineer/client_builder/build_schemas.py, mountaineer/client_builder/builder.py, mountaineer/js_compiler/javascript.py, mountaineer/test_utilities.py, mountaineer/watch.py, src/lib.rs, src/logging.rs, src/ssr.rs
We modify our watch logic to keep track of what files were actually modified. We bundle up this change log so the builder can determine the type of changes that were made. This speeds up builds by letting us do the minimum computation for each change type. More specifically:
If a _view_ file has changed but the _server_ has not, there's no reason to restart the python runtime and server codebase. We will keep the server running in our isolated watch process and just perform a rebuild of the client files.
If the server has updated but the _API_ has not changed, there's no reason to rebuild the `useServer` client hooks. Since our file building process is deterministic given the input OpenAPI schema, this will just result in the same files that were generated previously. At the moment we …
=> Partial JS Builds

mountaineer/__init__.py, mountaineer/__tests__/client_builder/test_builder.py, mountaineer/actions/__init__.py, mountaineer/database/__init__.py, mountaineer/database/dependencies/__init__.py, mountaineer/database/sqlmodel.py, mountaineer/dependencies/__init__.py, mountaineer/dependencies/base.py, mountaineer/js_compiler/source_maps.py, mountaineer/paths.py, pyproject.toml
Small conventional formatting change to ruff's default settings for isort. Group named imports coming from the same file to save on room, particularly within init aggregation exports.
=> Group imports in init files

mountaineer/__tests__/test_app.py, mountaineer/app.py
Some FastAPI arguments are only available at init time and can't be overridden after the fact. `lifespan` is one of these, which allows you to install custom hooks at the beginning and termination of your webapp process. To support these init arguments in a generic way, we add a new `fastapi_args` parameter to the AppController. At runtime we will pass these through as-declared so you can override any default argument that FastAPI supports now and in the future.
=> Optional passthrough of custom fastapi args

mountaineer/__tests__/test_app.py, mountaineer/app.py
Since we use the controller names to generate client javascript artifacts, we need them to have unique names. Validate this explicitly as part of the controller registration process to flag issues early.
=> Validate unique controller names

.gitignore, create_mountaineer_app/create_mountaineer_app/__tests__/test_builder.py, create_mountaineer_app/create_mountaineer_app/__tests__/test_cli.py, create_mountaineer_app/create_mountaineer_app/__tests__/test_generation.py, create_mountaineer_app/create_mountaineer_app/builder.py, create_mountaineer_app/create_mountaineer_app/cli.py, create_mountaineer_app/create_mountaineer_app/environments/base.py, create_mountaineer_app/create_mountaineer_app/environments/poetry.py, create_mountaineer_app/create_mountaineer_app/environments/venv.py, create_mountaineer_app/create_mountaineer_app/generation.py, create_mountaineer_app/create_mountaineer_app/templates/editor_configs/vim/.vimrc, create_mountaineer_app/create_mountaineer_app/templates/editor_configs/vscode/.vscode/settings.json, create_mountaineer_app/create_mountaineer_app/templates/editor_configs/zed/pyrightconfig.json, create_mountaineer_app/create_mountaineer_app/templates/project/pyproject.toml
The templated project files in `create-mountaineer-app` are highly coupled to the active Mountaineer version that's within `main`. This PR removes the hard-coded Mountaineer version from the CMA templating logic, to avoid human errors where we don't bump the Mountaineer template to the appropriate version.
After this is merged and released, we will pull the same version of Mountaineer that is built concurrently with CMA. We can do this by checking the current CMA version, since they're released with equivalent feature numbers (see [here](https://github.com/piercefreeman/mountaineer/blob/9d210d61fc3f1c341470268bd4c58c267f01fd04/.github/workflows/test_create_mountaineer_app.yml#L99) for the current logic).
Fixes https://github.com/piercefreeman/mountaineer/issues/77.
=> Pin mountaineer to CMA version

mountaineer/__tests__/actions/test_fields.py, mountaineer/__tests__/actions/test_passthrough.py, mountaineer/__tests__/actions/test_sideeffect.py, mountaineer/__tests__/client_builder/test_build_actions.py, mountaineer/__tests__/client_builder/test_build_schemas.py, mountaineer/__tests__/test_app.py, mountaineer/actions/fields.py, mountaineer/actions/sideeffect.py, mountaineer/app.py, mountaineer/client_builder/build_actions.py, mountaineer/client_builder/build_links.py, mountaineer/client_builder/build_schemas.py, mountaineer/client_builder/builder.py, mountaineer/client_builder/openapi.py, mountaineer/controller.py, mountaineer/exceptions.py, mountaineer/render.py
This PR fixes some edge cases with OpenAPI schema construction and parsing for use in JS generation.
Cookies accessed by method signatures will be captured in the raw OpenAPI schema. The client application will pass through these automatically with the `fetch()` defaults, so we allow our action builder to parse them but skip over them during the JS function construction.
We add stronger validation of user-provided APIExceptions:
- Ensure that only one status code is available for each action URL, since OpenAPI switches based on status code value.
- Allow multiple APIException subclasses that have the same name, as long as they're defined in separate files. In this case we fallback to naming the schema based on the module and class name to avoid conflicting schema definitions. The default …
=> Improve APIException processing and inheritance

.github/scripts/fix_mac_wheels.py, .github/workflows/test.yml
We've seen periodic issues (like during the [last](https://github.com/piercefreeman/mountaineer/actions/runs/8439195911/job/23113769124) release) where wheel artifacts created on OSX can't be read by twine. This issue notably only affects OSX artifacts.
Switching to an OSX runner fixed the frequency of these issues (likely because the underlying system zip utilities are more compatible) but hasn't completely solved the problem. This PR tries another approach where we run a compatibility check for the OSX artifacts and then unzip->rezip them at the system level. We then try to read these newly rezipped files at the python layer so we can throw an early error during the building if we expect to have problems when twine reads the file contents.
=> Attempt mac wheel fixes if corrupt

.github/workflows/test.yml, src_go/build.rs
PR to support older glibc versions to maximize prebuilt wheel compatibility. First raised in https://github.com/piercefreeman/mountaineer/issues/81.
Our initial approach was just to use the 20.04 runners, install golang globally, and then share the golang install with the docker context. Since the 20.04 runner will likely be deprecated when the support window expires (Apr 2025) we instead use the provided docker image for compilation. This has the added benefit of allowing us to cross-compile for more architectures. aarch64 was previously enabled but removed during the golang builder migration.
This glib support goes back to 2.17.
=> Build wheels for older glibc

.github/workflows/test.yml
The precompiled Mac wheel released as `0.3.2.dev1` had a compiled `.so` that would only run on x86 architectures. This new pipeline logic refactors `GOARCH` into a global environment variable within the build pipeline, so it should get used on host runs (mac, windows) while passing into the docker container for multilinux builds.
=> Fix wheel for aarch64 on mac

mountaineer/app.py, mountaineer/config.py, mountaineer/js_compiler/javascript.py
Add a ConfigBase convention for specifying the environment that the Mountaineer app is running under. We've always supported this via the `JavascriptBuilder`, but overriding the default of `development` required an explicit instantiation. This approach makes it much easier to override the environment via a environment variable that you can toggle as you deploy into remote environments.
Specifically, this `ENVIRONMENT` python key will make its way into the javascript environment (both in SSR and in the client side app) via the `process.env.NODE_ENV` key. Only if this key is equal to `development` will we add the WebSocket reloading instance to the global state. This also allows users to add additional conditional frontend logic depending on the environment.
=> Allow override of environment in config

mountaineer/__tests__/js_compiler/test_source_maps.py, mountaineer/__tests__/test_logging.py, mountaineer/logging.py, mountaineer/test_utilities.py, pyproject.toml
When used in downstream client apps, it's helpful for the logger to also output the timestamp that warnings have occurred. We add a default formatter to the `mountaineer.logging` logger constructor.
We also hopefully improve function benchmarking stability by adding a time budget for runs in python.
=> Add timestamp and tests for logger

mountaineer/__tests__/client_builder/test_build_schemas.py, mountaineer/client_builder/build_schemas.py, mountaineer/client_builder/openapi.py, mountaineer/client_builder/typescript.py
As identified in https://github.com/piercefreeman/mountaineer/issues/91, there are some cases where python->javascript schema compilation can result in the wrong types without throwing any errors during the build process. We want to correct these wherever possible. This PR expands our test case coverage for complex types and makes our logic a bit more flexible to deal with nested complex types. We also add support for passing typed tuples through to Typescript.
=> More robust handling for complex schema types

mountaineer/__tests__/client_builder/test_build_schemas.py, mountaineer/client_builder/build_schemas.py, poetry.lock, pyproject.toml
Our previous recursive walking in `gather_all_models.walk_models` would infinitely loop for self-referential refs. This PR fixes this recursion by keeping track of the parsed model names. These should be unique within one OpenAPI schema so we can reasonably use this as a unique identification key.
=> Handle recursive schema definitions

mountaineer/client_builder/builder.py
We leverage the local "/tmp" directory extensively in building so we can avoid polluting the local project filesystem until we are sure that we have a successful build result. Upon completion, we want to move files from the temporary directory to the local project. Mostly this is okay since we operate within the same device - but there are some situations (docker, remote CI builds, booting from removable storage) where the OS's default /tmp path is on a different volume than the project itself. Our previous logic would crash in these cases with a `Invalid cross-device link` error.
This PR fixes this bug by moving to shutil.move for moving temporary files. It will default to a regular replace while within the same volume and fallback to a copy/delete in the case of differing volumes.
``` …
```
=> Use shutil for cross-volume moves

mountaineer/cli.py, mountaineer/watch_server.py
There have been some observed instances of the watcher webservice not shutting down properly when terminated with a sig-int. Since the main cleanup that's important is for our watchdog process (which is process isolated), we do a best effort to shutdown the watch server but don't block the shutdown process because of it.
=> Time-limited join for watcher webservice

docs_website/docs/views.md, docs_website/mkdocs.yml, mountaineer/__tests__/client_builder/test_build_links.py, mountaineer/__tests__/client_builder/test_typescript.py, mountaineer/client_builder/typescript.py, mountaineer/static/api.ts
This PR adds support for render functions to specify list-based query parameters. This can be useful to persist client-side state that can be sent to other users, bookmarked, etc.
```python
from typing import Annotated
from fastapi import Query
class MyController(ControllerBase):
async def render(
self,
my_arg: Annotated[list[int] | None, Query()] = None,
):
pass
```
These list values will render in the URL of the final page like:
```
localhost:5006/my_page?my_arg=1&my_arg=2
```
And in the typescript signature like:
```typescript
export const getLink = ({
my_arg
}:{
my_arg?: Array<number> | null
}) => {
...
}
```
=> Support list-based page query params

ci_webapp/ci_webapp/cli.py, ci_webapp/ci_webapp/controllers/root_layout.py, ci_webapp/ci_webapp/views/app/layout.tsx, ci_webapp/pyproject.toml, docs_website/docs/views.md, mountaineer/__tests__/actions/test_fields.py, mountaineer/__tests__/actions/test_passthrough_dec.py, mountaineer/__tests__/actions/test_sideeffect_dec.py, mountaineer/__tests__/test_app.py, mountaineer/actions/fields.py, mountaineer/actions/passthrough_dec.py, mountaineer/actions/sideeffect_dec.py, mountaineer/app.py, mountaineer/client_builder/builder.py, mountaineer/static/api.ts
Follow-on PR to https://github.com/piercefreeman/mountaineer/pull/104, to bring layout controllers to full dependency injection parity as page controllers. We accomplish this by inspecting the signature of the page / layout endpoints during AppController registration, and progressively combine additional signatures as the pages come into scope. This allows us to keep the dynamic mode of controller registration with the AppController, while allowing the `render` methods of layout controllers to have the full scope of dependency injection arguments. This includes query parameters and request-based parameters, like extracting user headers.
A convenient benefit of our new implementation is that layout controllers will share the underlying dependency injected objects with the controller …
=> Merge signatures of layout and page controllers

docs_website/docs/api/database/migrations.md, docs_website/docs/client_actions.md, docs_website/docs/database_migrations.md, docs_website/mkdocs.yml, mountaineer/__tests__/migrations/test_actions.py, mountaineer/__tests__/migrations/test_db_serializer.py, mountaineer/__tests__/migrations/test_db_stubs.py, mountaineer/__tests__/migrations/test_generator.py, mountaineer/__tests__/migrations/test_handlers.py, mountaineer/migrations/actions.py, mountaineer/migrations/db_memory_serializer.py, mountaineer/migrations/db_serializer.py, mountaineer/migrations/db_stubs.py, mountaineer/migrations/dependency/__init__.py, mountaineer/migrations/generator.py, mountaineer/migrations/handlers.py, mountaineer/migrations/migration.py
This PR mainly addresses edge cases with our experimental data migration plugin.
- Add additional unit tests to check expected transformation when executed against Postgres. This validates the accuracy (and syntax) of our templated SQL queries.
- Workaround for dropping enums from existing table columns. Enums in Postgres can't be modified in-place, so the best workaround is to recreate them and then drop the old values. We now keep track of where enum values are referenced so we can migrate these to a new enum object that will replace the old one.
- Add support for "check" constraints.
- Modify a group of enum values at the same time (ie. pass all different enums) to avoid verbose migration files and repeated SQL commands to create/drop old enum types.
- Allow reserved table names within …
=> Fix database migration edge cases

docs_website/docs/database_migrations.md, mountaineer/__tests__/migrations/test_db_serializer.py, mountaineer/__tests__/migrations/test_db_stubs.py, mountaineer/__tests__/migrations/test_generator.py, mountaineer/__tests__/migrations/test_handlers.py, mountaineer/__tests__/test_io.py, mountaineer/client_builder/builder.py, mountaineer/client_builder/openapi.py, mountaineer/io.py, mountaineer/migrations/cli.py, mountaineer/migrations/db_memory_serializer.py, mountaineer/migrations/db_serializer.py, mountaineer/migrations/db_stubs.py, mountaineer/migrations/generator.py, mountaineer/migrations/handlers.py, mountaineer/migrations/migrator.py
- Support custom SQLAlchemy column constraint names, if users specify a `Field(sa_column)` attribute.
- Expand code generation support to set/frozenset/tuple types that are used in some cases.
- Fix potential freeze on database writes when running multiple migrations in a row; refactor out migration table creation to the top level CLI modules.
- Switch to DBTypePointer references in columns, instead of the fully serialized type object. While the previous method still yielded correct migrations, it might create redundant migration steps if attributes internal to the type object change but the rest of the column stays the same. We already take care of performing column-level migrations from within our type value migration action, so we instead should only migrate column types if the …
=> Expand support for migration edge cases

mountaineer/__tests__/test_cache.py, mountaineer/cache.py, mountaineer/cropper.py, mountaineer/database/dependencies/core.py
It's unusual in a webapp context, but some applications will need to have multiple asyncio event loops running in the same process context. Our previous approach to caching the AsyncEngine assumed we had a single global singleton whose objects could be used across all function users. This assumption fails in the context of multiple event loops, because SQLAlchemy internally creates a host of locks that are bound to the async runloop at the time of the first cached construction.
In this PR we refactor our convention to caching global async objects to use a `AsyncLoopObjectCache` helper class that manages the interaction between even loop and objects for us.
=> Cache database connection per event loop

Makefile, mountaineer/__tests__/actions/test_sideeffect_dec.py, mountaineer/__tests__/conftest.py, mountaineer/actions/sideeffect_dec.py, mountaineer/cli.py
Add unit tests and fix an edge case where query parameters weren't passed to the sideeffect re-rendering functions.
=> Pass query parameters to sideeffect re-renders

mountaineer/migrations/actions.py
Quote our foreign key relationships in our python->sql migration bridge, to avoid conflicts with postgres default columns like "user". These would fail otherwise when running the migration.
=> Fix reserved fields in foreign keys

mountaineer/annotation_helpers.py, mountaineer/database/sqlmodel.py, mountaineer/migrations/cli.py, mountaineer/migrations/handlers.py, poetry.lock, pyproject.toml
With the [release](https://github.com/tiangolo/sqlmodel/commit/95936bb5085b6ee467c4cd9051c7bfc8395c9b13) of sqlmodel's 0.0.20 release, they introduce full compatibility with SQLAlchemy's UUID class. We can therefore remove our class based workaround which causes a crash on lower sqlmodel versions.
We also add a new visual progress bar to our migration CLI for more obvious feedback about the completed migrations.
=> Align with sqlmodel's uuid refactor

Makefile, README.md, create_mountaineer_app/create_mountaineer_app/__tests__/test_builder.py, docs_website/docs/quickstart.md, docs_website/docs/structure.md
Github Actions have removed support for the `docker-compose` independent bin entrypoint. We switch to the modern `docker compose` so builds continue to succeed on CI.
=> Fix deprecated docker-compose command

README.md, create_mountaineer_app/create_mountaineer_app/templates/project/[project_name]/controllers/detail.py, create_mountaineer_app/create_mountaineer_app/templates/project/[project_name]/controllers/home.py, docs_website/docs/database_migrations.md, docs_website/docs/quickstart.md, docs_website/docs/views.md, mountaineer/__tests__/migrations/conftest.py, mountaineer/__tests__/migrations/test_actions.py, mountaineer/__tests__/migrations/test_db_serializer.py, mountaineer/database/cli.py, mountaineer/database/dependencies/core.py, mountaineer/database/session.py, mountaineer/migrations/actions.py, mountaineer/migrations/cli.py, mountaineer/migrations/db_serializer.py, mountaineer/migrations/migrator.py, mountaineer/test_utilities.py
Mountaineer's database support has focused on using a SQLAlchemy AsyncSession for database connections alongside SQLModel for query construction. This was due to some initial limitations in the async session provided by SQLModel and SQLAlchemy2.
Mixing the sessions works but can result in some clunky code. Each database request has to explicitly get the scalars for typehinting to resolve in mypy:
```python
query_result = await db_session.execute(query)
result = query_result.scalars().all()
```
Additionally, there are some cases where this approach results in the wrong typehints - like when we're trying to fetch a tuple of field:
```python
query = select(models.ModelA, models.ModelB)
```
We expect this would result in a tuple of (model_a, model_b) as the typehint suggests, but it only …
=> Use SQLModel Session for better typehinting

mountaineer/__tests__/actions/test_passthrough_dec.py, mountaineer/__tests__/actions/test_sideeffect_dec.py, mountaineer/actions/fields.py, mountaineer/actions/passthrough_dec.py, mountaineer/actions/sideeffect_dec.py
Previously, we would mirror our side-effect decorated return value both at runtime (through `@wraps`) and during static typechecking. However, this wouldn't be the actual value that's returned if you were to do a controller.my_sideeffect() call - which can be a bit confusing if you're interacting with side-effects directly and not proxying through a httpx web request in testing.
This PR updates our decorator typehints to typehint the actual return values of sideeffects and passthroughs - namely a dictionary of `sideeffect` and `passthrough` values. We also allow access to our original function via a new `.original` static function that is exposed to the returned function.
```python
controller = ExampleController()
await ExampleController.call_sideeffect.original(controller, dict())
await …
```
=> Update sideeffect typehints to reflect runtime

mountaineer/__tests__/client_builder/test_builder.py, mountaineer/client_builder/builder.py, mountaineer/static/api.ts
While it wouldn't halt compilation, our existing typescript generation logic had a few small issues that would throw errors during compilation. This PR fixes those to only include valid links, and add more specific type-hinting for errors defined in our standard `api` package.
=> Remove invalid dependencies from typescript files

mountaineer/__tests__/fixtures/mock_webapp/simple_classes_1.py, mountaineer/__tests__/fixtures/mock_webapp/simple_classes_2.py, mountaineer/__tests__/test_app_manager.py, mountaineer/app_manager.py, mountaineer/cli.py, mountaineer/migrations/actions.py, mountaineer/migrations/db_serializer.py, mountaineer/migrations/db_stubs.py, mountaineer/migrations/generator.py, mountaineer/migrations/handlers.py, poetry.lock
- Reload the modules that we can during hot-reloading, while ignoring any that are subject to syntax errors / load exceptions.
- Refresh the subclasses of the classes of a modified module, since the runtime will use a cache import of the superclass until it's reloaded explicitly.
- Add support for index generation in migrations.
We also add a new `MOUNTAINEER_HOT_RELOADING` env variable when running locally with `runserver`. This allows users to implement conditional business logic to only load heavy dependencies on the first run but not on subsequent differential reloads of the python runtime.
Typehinting in `MigrationGenerator` will be restored with the fix of https://github.com/microsoft/pyright/issues/8963
=> Exception handling during reload, subclass reload

mountaineer/__tests__/client_builder/test_build_schemas.py, mountaineer/__tests__/static/__init__.py, mountaineer/__tests__/static/harness/__tests__/api_test.ts, mountaineer/__tests__/static/harness/jest.config.js, mountaineer/__tests__/static/harness/package-lock.json, mountaineer/__tests__/static/harness/package.json, mountaineer/__tests__/static/test_static.py, mountaineer/client_builder/build_actions.py, mountaineer/client_builder/build_schemas.py, mountaineer/client_builder/typescript.py, mountaineer/static/api.ts
Add support for multipart form action functions. The server-side API was already enabled correctly, but our frontend didn't provide the correct model typehints (weren't camel-cased properly) or support for multipart form requests. We update the builder logic here to correct these definitions. We also add proper unit tests for the `api.ts` file that is growing in complexity.
=> Support multipart Form payloads

mountaineer/app.py, mountaineer/client_builder/openapi.py, mountaineer/controller.py, mountaineer/paths.py, poetry.lock
Our previous check for a non-null render metadata before global metadata merge meant that page that didn't have any metadata specified wouldn't be merged with the global payload. This PR ensures we fallback to global metadata in all cases.
=> Fallback to global metadata

mountaineer/__tests__/controllers/test_traceback.py, mountaineer/__tests__/fixtures/mock_webapp/simple_controller.py, mountaineer/__tests__/test_app_manager.py, mountaineer/__tests__/test_hotreload.py, mountaineer/app_manager.py, mountaineer/controllers/exception_controller.py, mountaineer/controllers/traceback.py, mountaineer/views/core/exception/page.tsx, mountaineer/views/core/layout.tsx, poetry.lock, pyproject.toml
This PR introduces an in-browser debugging workflow for Python exceptions. Our new exception parser lives in `controllers.hotreload` and is responsible for chunking out exceptions from different files and marking them up with syntax highlighting. This was inspired by the super useful traceback interface that we use in the backend from [rich](https://github.com/Textualize/rich/tree/master).
In addition to a simple stack trace, we also:
- Chunk out more context for each frame within the stack
- Parse the local variables that are still attached to the frame. To dig into what context caused the error, you can click on the function name to reveal the variable window.
=> Add exception parsing and styling

mountaineer/__tests__/client_builder/test_builder.py, mountaineer/__tests__/client_compiler/test_compile.py, mountaineer/__tests__/test_render.py, mountaineer/app.py, mountaineer/app_manager.py, mountaineer/cli.py, mountaineer/client_builder/builder.py, mountaineer/client_compiler/base.py, mountaineer/client_compiler/build_metadata.py, mountaineer/client_compiler/compile.py, mountaineer/client_compiler/postcss.py, mountaineer/hotreload.py, mountaineer/logging.py, mountaineer/paths.py, mountaineer/render.py
Websites typically want aggressive caching policies on their static directory, since support files like css/js only change during a deployment of a new version. While it's possible to handle this in other ways (ie. 304 Not Modified) it's cleaner to handle this at the framework level. The new logic in this PR will analyze the _static folder at build time, cache the current version of the file sha, and inject this into any `LinkAttributes` that import this file.
Closes out https://github.com/piercefreeman/mountaineer/issues/133
=> Automatically add sha to static artifacts

poetry.lock, pyproject.toml
Our wheel publishing is currently failing with:
```
Checking dist/mountaineer-0.8.0.dev3-cp310-cp310-macosx_10_12_x86_64.whl: ERROR    InvalidDistribution: Metadata is missing required fields: Name,        
Version.                                                               
Make sure the distribution includes the files where those fields are   
specified, and is using a supported Metadata-Version: 1.0, 1.1, 1.2,   
2.0, 2.1, 2.2, 2.3.
```
This was caused by maturin's bump to 1.7.6, which now creates wheels that use metadata 2.4. Twine doesn't yet support this format so throws an error upon validation.
Pinned maturin ticket: https://github.com/PyO3/maturin/issues/2335
Our CI pipeline automatically pulls the latest maturin version by inspecting any constraints placed within pypi - …
=> Pin maturin to use metadata 2.3

Makefile, mountaineer/__tests__/client_builder/file_generators/test_globals.py, mountaineer/__tests__/client_builder/file_generators/test_locals.py, mountaineer/__tests__/client_builder/interface_builders/common.py, mountaineer/__tests__/client_builder/interface_builders/test_action.py, mountaineer/__tests__/client_builder/interface_builders/test_base.py, mountaineer/__tests__/client_builder/interface_builders/test_controller.py, mountaineer/__tests__/client_builder/interface_builders/test_enum.py, mountaineer/__tests__/client_builder/interface_builders/test_exception.py, mountaineer/__tests__/client_builder/interface_builders/test_model.py, mountaineer/__tests__/client_builder/test_aliases.py, mountaineer/__tests__/client_builder/test_parser.py, mountaineer/__tests__/client_builder/test_types.py, mountaineer/app.py, mountaineer/client_builder/aliases.py, mountaineer/client_builder/file_generators/base.py, mountaineer/client_builder/file_generators/globals.py, mountaineer/client_builder/interface_builders/action.py, mountaineer/client_builder/interface_builders/enum.py, mountaineer/client_builder/parser.py, mountaineer/client_builder/types.py, mountaineer/ssr.py, poetry.lock, pyproject.toml, src/benches/fixtures/ssr_polyfill_archive.js
Full test coverage for https://github.com/piercefreeman/mountaineer/pull/145.
=> Test suite for global models and interfaces

mountaineer/__tests__/client_builder/test_parser.py, mountaineer/__tests__/static/harness/__tests__/api_test.ts, mountaineer/__tests__/test_app.py, mountaineer/actions/fields.py, mountaineer/actions/passthrough_dec.py, mountaineer/actions/sideeffect_dec.py, mountaineer/app.py, mountaineer/client_builder/interface_builders/action.py, mountaineer/client_builder/parser.py, mountaineer/exceptions.py, mountaineer/static/api.ts
If a client action request fails to validate the method signature, the FastAPI server layer will raise a `RequestValidationError` with metadata about what failed to validate. This PR makes this error response more explicit by adding it automatically to the `@sideeffect` and `@passthrough` decorators, which in turn generates the definitions for use in controller models.
=> Structure 422 unprocessable entities & support typehinted headers

mountaineer/__tests__/static/harness/jest.config.js, mountaineer/__tests__/static/harness/package.json, mountaineer/static/api.ts
API actions use relative urls to access the main web service's API consistently across different hosts (local, dev, prod, etc). This is incompatible with the single parameter URL object construction because it only doesn't automatically parse the window's current location. We fix this in this PR by explicitly passing the window root to new url constructors so it should automatically fallback when no host is found in our relative action queries.
=> Pass fallback origin to JS URL

.github/scripts/__tests__/test_update_version.py, .github/scripts/update_version.py
We've assumed that all pyproject.toml file will include a poetry section during our automatic version bump. This might not be true for packages that switch to management by `uv`.
=> Skip updating poetry section if not available

docs/guides/structure/page.mdx, docs/guides/views/layout-organization.mdx, docs/guides/views/page.mdx
This pull request introduces the ability to disable layouts for specific controllers. The main use case for this new functionality is to allow the "index", "login", etc. pages to not rely on a global layout.
@piercefreeman Let me know if you think it would be better to have layout overriding instead
=> feat: optional layouts

.github/workflows/test.yml, docs/api/logging/page.mdx, mountaineer/logging.py, src/ssr.rs
When V8 is initialized on a non-main thread on CPU architectures that have PKU enabled, rendering can occasionally crash during memory allocation:
```
Thread 36 "python" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff69e006c0 (LWP 134254)]
0x00007ffff2f728b1 in v8::internal::FreeListManyCachedFastPathBase::Allocate(unsigned long, unsigned long*, v8::internal::AllocationOrigin) ()
```
When this happens a SIGSEGV is thrown in the V8 isolate itself, which is caught by neither Rust nor Python so the application exits with no further context about the issue.
The official workaround used by the Deno downstream is to always call the singleton initialization in the main process to avoid this issue from occurring:
https://github.com/denoland/rusty_v8/issues/1381
=> Fix nondeterministic crash on pku flags

Cargo.lock, Cargo.toml, Makefile, src/bundle_common.rs, src/bundle_independent.rs, src/lib.rs, src/logging.rs, src/ssr.rs
Our Python internal logger uses the `MOUNTAINEER_LOG_LEVEL` to determine the logging verbosity, but previously our rust logging was separate and had to be configured with build-time flags. This PR adds a logging configuration in rust that mirrors the Python configurations. It should be available globally for all py03 built functions.
=> Update rust to align with python logging

create_mountaineer_app/create_mountaineer_app/__tests__/test_builder.py, create_mountaineer_app/create_mountaineer_app/__tests__/test_generation.py, create_mountaineer_app/create_mountaineer_app/builder.py, create_mountaineer_app/create_mountaineer_app/cli.py, create_mountaineer_app/create_mountaineer_app/enums.py, create_mountaineer_app/create_mountaineer_app/environments/__init__.py, create_mountaineer_app/create_mountaineer_app/environments/uv.py, create_mountaineer_app/create_mountaineer_app/generation.py, create_mountaineer_app/create_mountaineer_app/templates/project/pyproject.toml
Add support for managing mountaineer projects generated by CMA with `uv`. Like the poetry and venv installers, this will ensure the local environment has the manager installed & then install the dependencies during setup.
=> Add uv support to CMA

create_mountaineer_app/pyproject.toml, create_mountaineer_app/uv.lock
```
_________________________________________________________________________ ERROR collecting create_mountaineer_app/__tests__/test_builder.py _________________________________________________________________________
ImportError while importing test module '/Users/matthewlemay/Github/mountaineer/create_mountaineer_app/create_mountaineer_app/__tests__/test_builder.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
.venv/lib/python3.10/site-packages/_pytest/python.py:493: in importtestmodule
mod = import_path(
.venv/lib/python3.10/site-packages/_pytest/pathlib.py:587: in import_path
importlib.import_module(module_name)
../../../.local/share/uv/python/cpython-3.10.15-macos-aarch64-none/lib/python3.10/importlib/__init__.py:126: in import_module
return …
```
=> fix: psycopg binary

mountaineer/__tests__/actions/test_sideeffect_dec.py, mountaineer/actions/sideeffect_dec.py
Fixes an error (see below) that occurs when rending a layout with state. For context this is my use case.
```python
class AuthLayoutController(LayoutControllerBase):
view_path = "/app/(auth)/layout.tsx"
async def render(
self,
conn: Connection,
user: CurrentUser,
organization: CurrentOrganization,
) -> AuthLayoutRender:
memberships = await OrganizationMembership.by_user(conn=conn, user=user)
return AuthLayoutRender(organization=organization, user=user, memberships=memberships)
```
```
[quick-castle]:   File "/Users/matthewlemay/Github/brugge/.venv/lib/python3.13/site-packages/logfire/_internal/integrations/fastapi.py", line 138, in patched_run_endpoint_function
[quick-castle]:     return await instrumentation.run_endpoint_function(
[quick-castle]: …
```
=> fix: layout sessions

create_mountaineer_app/README.md, create_mountaineer_app/pyproject.toml
Somewhere in our build pipeline changes (likely the switch the hatchling as the build backend for CMA), we started excluding the default generated .env when users request a default database integration. This PR restores that file to allow the first run to succeed as expected.
=> Include .env template in CMA

mountaineer/__tests__/client_compiler/test_postcss.py, mountaineer/client_compiler/postcss.py
Some environments don't pick up on our relative directories pointing to postcss. This PR updates these paths to absolute and adds basic (non-integration) tests verifying this behavior.
=> Hardset paths for postcss location

create_mountaineer_app/create_mountaineer_app/templates/project/[project_name]/views/package.json, mountaineer/app.py, mountaineer/cli.py, mountaineer/controller.py
We don't want to re-build controllers that are part of plugins, since we have already enforced that they're bundled with the appropriate code on .register. Re-building will create excessive artifact noise and maybe require dependencies that we don't have installed locally.
=> Only build client, non-plugin dependencies

Cargo.lock, Cargo.toml, mountaineer/app.py, src/bundle_common.rs, src/bundle_independent.rs, src/code_gen.rs, src/errors.rs, src/logging.rs, src/source_map.rs, src/ssr.rs
We originally tried to update rolldown to a more modern version, but ran into node_module package resolution errors because of the removal of [modules](https://github.com/rolldown/rolldown/pull/4392). Setting the cwd param didn't address the path references (nor did symlinking in tmp).
We bump to the latest version right before that change and update the development script imports to use "module" resolution within local javascript. Otherwise we can see errors when ESM outputs "import.meta" code like in [zustland](https://github.com/pmndrs/zustand/issues/1392).
=> Bump rolldown and make debug a module import
